Fix factor colour
stemangiola/tidyHeatmap pull request #131
Opened 2024-07-12 04:47 UTC by william-hutchison

If a factor is used to annotate the heatmap, the order of colours provided to `palette` will now match the order of the factor levels. 

Previously, the `colorRampPalette(palette_annotation$discrete[[.y]])(length(unique(.x))) %>% setNames(unique(.x))` was used to assign factor levels their colour, which does not consider factor level order. 

This PR fixes issue #113

2024-08-01 04:07 UTC, stemangiola commented
Amazing, remember that for each PR you should have unit test that proofs you fix. In you changed files I see a lot of plots that change color palette scheme. Is this related with you PR?

Also see what issues this PR can be linked to, I think there are couple of issues, and I also tried to solve this without success if I remember well.

2024-08-01 05:51 UTC, william-hutchison commented
Hi Stefano,

I have linked the PR to issue #113 in the description, but don't think I have access to link using the actual development dropdown menu. 

I can't quite remember why, but it seems factors previously always used a grey colour for one value and then rotated through the rest of the default palette. Maybe the grey colour was intended for NA values, but not being used because the levels were not correctly assigned. Whatever the cause, I think the new output is more in line with what the user might expect when using the default palette.

Thank you for the suggestion, I have added a unit test which explicitly tests for annotation tile factor level colour palette order.

2024-08-02 11:23 UTC, stemangiola approved these changes

2024-08-02 12:19 UTC, stemangiola requested changes

2024-08-02 12:19 UTC, stemangiola commented on tests/testthat/tests.R
> +  p =
Can you please add another test where you manipulate the factor order 

```r
levels = c( "second_level", "third_level", "fourth_level", "first_level")
```

And you test the effect

2024-08-05 06:55 UTC, merged